name: Build and deploy Python app to Azure Web App - test-python-learning-django-github

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test-python-learning-django-github'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f724911c038a40aca1741585c4f9e268 }}
